apiVersion: v1
kind: Service
metadata:
  name: league-ladder-service
  namespace: default
spec:
  selector:
    app: league-ladder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer